name: Arduino Validation

on: [push, pull_request]

jobs:
  sketch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Arduino sketch exists
        run: |
          if find Arduino_Code -name "*.ino" | grep -q .; then
            echo "Arduino sketch found."
          else
            echo "No Arduino sketch found."
            exit 1
          fi
